-- Nuke everything and recreate schema
drop schema public cascade;
create schema public;
grant all on schema public to postgres;
grant all on schema public to public;
grant usage on schema public to postgres;
grant usage on schema public to public;
grant all on all tables in schema public to postgres;
grant all on all tables in schema public to public;
grant all on all sequences in schema public to postgres;
grant all on all sequences in schema public to public;
grant all on all functions in schema public to postgres;
grant all on all functions in schema public to public;

-- Create the people_cards table
create table people_cards (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  project_name text,
  name text,
  profile_photo text,
  linkedin_url text,
  current_position text,
  concise_role text,
  key_achievements jsonb default '[]',
  professional_background text,
  career_history jsonb default '[]',
  expertise_areas jsonb default '[]',
  CONSTRAINT unique_person_in_project UNIQUE (project_name, name)
);

-- Enable RLS
alter table people_cards enable row level security;

-- Create a more permissive policy that allows all operations
drop policy if exists "all_access" on people_cards;
create policy "enable_all_access" on people_cards
  for all
  to public
  using (true)
  with check (true);

-- Ensure public can access the table
grant all privileges on table people_cards to public;
grant all privileges on sequence people_cards_id_seq to public;

-- Create index for project lookups
create index on people_cards (project_name); 